### ISSUE TITLE
GISAID data download method

### ISSUE THREAD

**Issue by qianqli** [cyrusmaher/MutationEpiScore#5]
Dear Cyrusmaher, 

When I run the GISAID data downloaded directly, there is the error: 
" raise KeyError(list(np.compress(check, subset)))
KeyError: ['AA Substitutions', 'Location']",

I checked the original metadata,  and there are variables "location" but no "AA Substitutions" or related variables at all.  So I want to ask, how do you download the data, and could you share the methods or codes (the GISAID allows downloading 5000 once,  I think there should be some other methods here)? 

Kind Regards
QIanqian

**Comment by cyrusmaher** [comment]
Unfortunately GISAID is fairly inconsistent, and how the data can be accessed varies according to the account. In your data download, can you access the amino acid subsitutions per sequence? "AA Substitutions" is just a comma separated list of these substitutions, with each mutation prefixed by "{gene_name}_"

**Comment by cyrusmaher** [comment]
I've added an example metadata file in the format we download from GISAID: https://github.com/cyrusmaher/MutationEpiScore/blob/main/metadata_example.tsv

**Comment by qianqli** [comment]
Dear Cyrusmaher, 

I am really thankful for your reply and the example. Unfortunately, for my account, there is no "AA substitutions" column in the meatadata. And finally, I found that my account has no right to access the download packages. 

Thanks.
Qianqian
